In [56]:
myList = [10, 20, 30, 40, 50]
type(myList)

list

1st difference:

    numpy array: immutable. when adjusting the variables inside an array, a new array is created to store

    on constrast: list in python is different. can be append() or pop() (i.e. increase or decrease the size) 

2nd difference:

    numpy array: can only contain one type of data type: int, float, or string 
    
    python list: can have combine structure  

3rd:
 
    python list: is resource consume. not as efficient as numpy array. 


In [57]:
import numpy as np

In [58]:
np

<module 'numpy' from 'C:\\Users\\dqthi\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\__init__.py'>

In [59]:
a = np.array([10, 20, 30 , 40, 50 ])

In [60]:
a

array([10, 20, 30, 40, 50])

In [61]:
type(a)

numpy.ndarray

In [62]:
a

array([10, 20, 30, 40, 50])

In [63]:
myList

[10, 20, 30, 40, 50]

In [64]:
a = np.array(myList)

In [65]:
type(a)

numpy.ndarray

In [66]:
a

array([10, 20, 30, 40, 50])

In [67]:
a[0]

np.int64(10)

In [68]:
a[1]

np.int64(20)

In [69]:
print (a[1])

20


In [70]:
print (a[0])

10


In [71]:
a[-1]

np.int64(50)

In [72]:
for one_item in a: 
    print(one_item)

10
20
30
40
50


In [73]:
a

array([10, 20, 30, 40, 50])

In [74]:
20 in a

True

In [75]:
a[2:4]

array([30, 40])

In [76]:
a[::2]

array([10, 30, 50])

In [77]:
a[2]

np.int64(30)

In [78]:
a[2] = 999
a

array([ 10,  20, 999,  40,  50])

In [79]:
# numpy has several behaviour like list, but actually it is not.  

In [80]:
a.append(60)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
# we are stuck with the length of the array, unlike python list whereas we can add(increase size) or remove (decrease size) 
# => numpy array fixed size 

In [32]:
b =  np.array(range(10, 110, 10))

In [33]:
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [35]:
b =  np.arange(10, 110, 10)  # start_index, end_index + 1, step_size 

In [36]:
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Exercise

(1) Create a NumPy array with the integers from your birthdate (year,
    month, and day)

(2) Retrieve the year.

(3) Replace the year with the current year.

(4) Create a NumPy array containing every 3rd number from 567 to
    890. What is the 8th number in this array?  What is the 15th?

In [37]:
date_birth  = np.array([1988, 10, 30])

In [38]:
print(date_birth[0])

1988


In [39]:
date_birth[0] = 2024

In [40]:
print(date_birth[0])

2024


In [47]:
random_exercise = np.arange(567, 890+3, 3)

In [48]:
random_exercise

array([567, 570, 573, 576, 579, 582, 585, 588, 591, 594, 597, 600, 603,
       606, 609, 612, 615, 618, 621, 624, 627, 630, 633, 636, 639, 642,
       645, 648, 651, 654, 657, 660, 663, 666, 669, 672, 675, 678, 681,
       684, 687, 690, 693, 696, 699, 702, 705, 708, 711, 714, 717, 720,
       723, 726, 729, 732, 735, 738, 741, 744, 747, 750, 753, 756, 759,
       762, 765, 768, 771, 774, 777, 780, 783, 786, 789, 792, 795, 798,
       801, 804, 807, 810, 813, 816, 819, 822, 825, 828, 831, 834, 837,
       840, 843, 846, 849, 852, 855, 858, 861, 864, 867, 870, 873, 876,
       879, 882, 885, 888, 891])

In [49]:
random_exercise[7]  

np.int64(588)

In [50]:
random_exercise[14]

np.int64(609)

In [51]:
np.random.randint(0, 100, 10)   

array([12,  6, 72, 98, 35, 32, 52, 86, 53, 74], dtype=int32)

In [52]:
np.random.randint(0, 100, 10)

array([24, 33, 87, 99,  9, 53,  8,  4, 19, 46], dtype=int32)

In [54]:
np.random.randint(0, 100, 1000)

array([97, 46, 77, 34, 52, 59, 85, 17, 18, 61, 57, 51, 83, 95,  1, 30, 93,
       97, 10, 44, 55,  5,  5, 41, 94, 94, 10, 39, 90, 37, 59, 51, 20, 52,
       33, 85, 72, 88, 47, 47, 33, 81, 95, 73, 86, 99, 86, 20, 68, 25, 21,
       57, 91, 23, 19, 90, 22, 73, 73, 35, 91, 10, 25, 92, 14, 56, 50, 45,
       73, 45, 47,  9, 73, 14, 30, 25, 31, 19, 31, 84, 84, 49, 34, 79, 97,
       59, 89, 86, 37, 17, 88, 84, 92, 41, 36, 90, 76, 28, 34, 35, 94, 91,
       66, 73, 29, 86, 35, 98,  1, 89, 59,  1, 68, 55, 60, 34, 51, 90, 74,
       11, 54, 43, 95, 78, 18, 49, 15, 39, 74, 10, 38, 53, 80, 31, 89, 99,
       99, 81, 96, 60, 20, 95, 71, 85, 17, 96, 80, 37, 35, 11, 65, 19, 64,
       13,  8, 88, 98, 25, 93, 67, 38, 53, 48,  2, 98, 72,  5, 98, 64, 27,
       76, 70, 68, 10, 85,  0,  5, 70, 42, 16, 57, 26, 90, 11, 44, 70, 74,
       75, 11, 35, 98, 33, 33, 87, 87,  0, 64, 67, 58, 90, 93, 36, 35, 86,
        7, 55, 45,  2, 10, 58, 66,  4, 67, 44, 68, 74, 12, 91, 11, 15,  4,
       93, 59, 62, 56, 54

In [55]:
help(np.random.randint)

Help on method randint in module numpy.random.mtrand:

randint(low, high=None, size=None, dtype=<class 'int'>) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional

In [56]:
np.random.rand(10) # creating floating numbers between 0 and 1 

array([0.03064869, 0.10673882, 0.98055845, 0.59437702, 0.27476696,
       0.70000257, 0.98937587, 0.00253565, 0.38798015, 0.44482991])

In [59]:
c = np.random.randint(0, 100, 10)
c

array([96, 64, 93, 48, 64, 54, 15, 94, 10,  6], dtype=int32)

In [66]:
np.random.seed(1)
c = np.random.randint(0, 100, 10)
c

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1], dtype=int32)

In [69]:
help (np.random.seed) # still not able to understand the actual machanical running behind, I can put it in a simple term is this method will make sure the same set numbers will be generate when we run random :) 
                        # not quite sure how changing the arguments will impact the function of this method 

Help on cython_function_or_method in module numpy.random.mtrand:

seed(seed=None)
    seed(seed=None)
    
    Reseed the singleton RandomState instance.
    
    Notes
    -----
    This is a convenience, legacy function that exists to support
    older code that uses the singleton RandomState. Best practice
    is to use a dedicated ``Generator`` instance rather than
    the random variate generation methods exposed directly in
    the random module.
    
    See Also
    --------
    numpy.random.Generator



# vectorized operations with two arrays 

In [70]:
a  = np.array(myList)

In [71]:
a

array([10, 20, 30, 40, 50])

In [72]:
a + a 

array([ 20,  40,  60,  80, 100])

In [73]:
b = np.array([100, 200, 300, 400, 500])

a + b

array([110, 220, 330, 440, 550])

In [74]:
a - b

array([ -90, -180, -270, -360, -450])

In [75]:
a/b

array([0.1, 0.1, 0.1, 0.1, 0.1])

*does not work if the arrays are not in the same size or length* 

In [76]:
a = np.array(myList)

In [77]:
a

array([10, 20, 30, 40, 50])

In [78]:
a.sum() # method version  

np.int64(150)

In [79]:
np.sum(a)

np.int64(150)

In [30]:
a.mean()

np.float64(223.8)

In [81]:
a.size

5

In [29]:
a.size() 

TypeError: 'int' object is not callable

In [28]:
a.mean()

np.float64(223.8)

In [27]:
a.sum() / a.size

np.float64(223.8)

In [81]:
a = np.array([30, 25, 35, 25, 35, 30])

In [82]:
a.mean() 

np.float64(30.0)

In [83]:
a.std() 

np.float64(4.08248290463863)

In [84]:
a = np.ones(5) *30
a

array([30., 30., 30., 30., 30.])

In [85]:
a.mean()

np.float64(30.0)

In [86]:
a.std() 

np.float64(0.0)

In [87]:
a = np.array([10, 20, 30 , 40, 50 ])

In [88]:
a.min() 

np.int64(10)

In [89]:
a.max() 

np.int64(50)

In [90]:
print (a.max())

50


#### Exercise 2: 
(1) Create an array of 10 random integers, from 0-100.

(2) Find the mean and standard deviation of these numbers.  

(3) Create another array of 10 random integers, from 0-100.

(4) Create a new array whose elements are the average of those from
    each of the previous ones.  

(5) Create an array of 10 random floats, from 0-100.

(6) We would expect the mean to be approaximately 50.  Is it?  What's
    the standard deviation?

(7) What are the min and max values?


In [105]:
exercise2a = np.random.randint(0, 100, 10)
exercise2a

array([75, 55, 20, 14,  2, 80, 78, 24, 91, 34], dtype=int32)

In [106]:
exercise2a.mean()


np.float64(47.3)

In [107]:
exercise2a.std() 

np.float64(30.617152055669713)

In [108]:
exercise2b = np.random.randint(0, 100, 10)
exercise2b

array([90, 10, 29, 63, 51, 69, 24, 17, 49, 16], dtype=int32)

In [109]:
type(exercise2a)

numpy.ndarray

In [110]:

exercise2c = exercise2b.mean()

In [112]:
print(exercise2c)

41.8


In [115]:
exercise2d = np.random.uniform(0, 100, 10)
exercise2d

array([52.15569236, 53.23338522, 46.16725809, 88.17419877, 20.123059  ,
       14.28742957, 80.03636225, 34.25058756, 19.36707178, 73.7955575 ])

In [116]:
exercise2d.std() 

np.float64(25.05198943419966)

In [117]:
exercise2d.mean()

np.float64(48.159060208616026)

In [118]:
exercise2d.max()

np.float64(88.17419876677096)

In [119]:
exercise2d.min()

np.float64(14.287429565391873)