In [1]:
import numpy as np

In [2]:
myList = [10, 20, 30]
myList

[10, 20, 30]

In [3]:
myList[1] = 100
myList

[10, 100, 30]

In [4]:
myList[1] = 100.50
myList


[10, 100.5, 30]

In [5]:
a  = np.array([10, 20, 30])

In [6]:
a

array([10, 20, 30])

In [7]:
a[1] = 100
a

array([ 10, 100,  30])

In [8]:
a[1] = 100.25

In [9]:
a

array([ 10, 100,  30])

python way: type(x) is a point to. the list does know what type of it content 
in numpy, there is an array of something => if I set the number.array as interger, it will set the default datatype of numpy is interger 
every numpy array has its own dtype 

In [10]:
a.dtype

dtype('int64')

In [11]:
dtype('int64')

NameError: name 'dtype' is not defined

In [12]:
dtype('int64')

NameError: name 'dtype' is not defined

In [13]:
np.dtype('int64')

dtype('int64')

In [14]:
np.int64

numpy.int64

In [16]:

np.int64 == np.dtype('int64')

True

In [17]:
a = np.random.randint(0, 100, 20)

In [18]:
a.dtype

dtype('int32')

In [21]:
a = np.random.rand(20)  * 100

In [22]:
a

array([75.06515411, 60.58056091, 59.15896462, 93.56735933, 89.39604221,
       33.58883656, 99.79566043, 10.07784387, 62.2345944 , 34.25172392,
       27.77759635, 82.52217265, 78.95970651, 56.50323232, 24.09706272,
       69.7345784 , 54.17977371, 37.6972909 , 91.39218133, 73.63763907])

In [23]:
a.dtype


dtype('float64')

In [24]:

a[0] ='abcd'

ValueError: could not convert string to float: 'abcd'

### Recap: 
- np array is datatype is presetted with type assigned, once it is assigned, it can not be changed

#### Setting dtypes 

In [25]:
a = np.array([10, 20, 30])
a.dtype

dtype('int64')

In [26]:
a = np.array([10, 20.5, 30])
a.dtype

dtype('float64')

In [27]:
a = np.array([10, '20.5', 30])
a.dtype

dtype('<U21')

In [28]:
a

array(['10', '20.5', '30'], dtype='<U21')

In [ ]:
# U21 is Unicode character 

In [29]:
a.sum()

TypeError: the resolved dtypes are not compatible with add.reduce. Resolved (dtype('<U21'), dtype('<U21'), dtype('<U42'))

In [30]:
a = np.array([10, 20, 30])
a.dtype

dtype('int64')

In [32]:
a = np.array([10, 20, 30], dtype=np.int8)

a.dtype

dtype('int8')

In [33]:
a

array([10, 20, 30], dtype=int8)

In [ ]:
# the phrase [dtype=np.int8], or [dtype=np.float64], or other dtype setting

#### Setting the dtype attribute 

In [34]:
a = np.array([10, 20, 30, 40, 50])

a.dtype

dtype('int64')

In [35]:
a[2]


np.int64(30)

In [36]:
a[2] =30.25

In [37]:
a

array([10, 20, 30, 40, 50])

In [38]:
a.dtype

dtype('int64')

In [39]:
a.dtype = np.float64

In [40]:
a

array([4.94e-323, 9.88e-323, 1.48e-322, 1.98e-322, 2.47e-322])

In [ ]:
# dtype should not be changed, rather being read or setting by default of the dataset 

#### Using Astype 

In [41]:
a = np.array([10, 20, 30, 40, 50])

a.dtype

dtype('int64')

In [42]:
a.astype(np.float64)

array([10., 20., 30., 40., 50.])

In [43]:
b = a.astype(np.float64)

In [44]:
b

array([10., 20., 30., 40., 50.])

In [45]:
b[2] =30.5

In [46]:
b

array([10. , 20. , 30.5, 40. , 50. ])

#### I want to use .astype(np.[type]) to change the datatype

#### String lengths

In [47]:
a = np.array('this is a test'.split())

In [48]:
a

array(['this', 'is', 'a', 'test'], dtype='<U4')

In [49]:
a[0]

np.str_('this')

In [50]:
a[0] = 'that'

In [51]:
a

array(['that', 'is', 'a', 'test'], dtype='<U4')

In [52]:
a[0] = 'the following sentence'

In [53]:
a

array(['the ', 'is', 'a', 'test'], dtype='<U4')

#### Exercise 6 


In [112]:
a = np.random.randint(0, 100, 10)
a

array([64, 55, 22, 94,  5, 50, 26, 20,  3, 41], dtype=int32)

In [113]:
a.astype(np.float64)

array([64., 55., 22., 94.,  5., 50., 26., 20.,  3., 41.])

In [114]:
a.mean()

np.float64(38.0)

In [115]:
a.std()

np.float64(27.003703449712226)

In [116]:
a[ (a > (a.mean() - a.std())) &
  (a < (a.mean() + a.std()))]

array([64, 55, 22, 50, 26, 20, 41], dtype=int32)

In [117]:
a.astype(np.float64)

array([64., 55., 22., 94.,  5., 50., 26., 20.,  3., 41.])

In [118]:
a.dtype 

dtype('int32')

In [120]:
a = a.astype(np.float64) # remember to save the variable after the formating assignment 
a[ (a < (a.mean() - a.std())) |
  (a > (a.mean() + a.std()))] = a.mean() 
a

array([39.2, 39.2, 39.2, 38. , 38. , 50. , 26. , 39.2, 38. , 41. ])

In [75]:
outliner = a[ (a < (a.mean() - a.std())) |
  (a > (a.mean() + a.std()))].astype(np.float64) 


In [79]:
outliner

array([87., 89., 94., 21., 28.])

In [82]:
outliner.dtype

dtype('float64')

In [83]:
outliner = a.mean()

In [84]:
outliner

np.float64(57.9)

In [121]:
a = np.random.rand(20) * 100
a

array([39.44730035, 11.54446277, 60.52499692, 69.84627872, 56.97454927,
       90.86858805, 35.31713618, 80.73822878, 37.12338642, 11.04200883,
       98.15108891, 78.475427  , 47.31475437, 76.37552327, 61.11744484,
       48.88912157,  4.62707029, 77.41337718, 73.48531947, 69.05661811])

In [122]:
a[a.astype(np.int64) % 2 == 0] = a.mean()

In [123]:
a

array([39.44730035, 11.54446277, 56.41663407, 69.84627872, 56.41663407,
       56.41663407, 35.31713618, 56.41663407, 37.12338642, 11.04200883,
       56.41663407, 56.41663407, 47.31475437, 56.41663407, 61.11744484,
       56.41663407, 56.41663407, 77.41337718, 73.48531947, 69.05661811])

#### Complex numbers

In [126]:
a = 2 + 3j 
b = 4 + 5j

In [127]:
a + b 

(6+8j)

In [128]:
type(a)

complex

In [129]:
type(b)

complex

In [130]:
a = np.array([10, 20, 30, 40, 50], dtype = np.complex64)
a

array([10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j, 50.+0.j], dtype=complex64)

In [131]:
a + 3
a

array([10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j, 50.+0.j], dtype=complex64)

In [132]:
a +  1 + 2.2J
a

array([10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j, 50.+0.j], dtype=complex64)

In [133]:
a + 2.2j

array([10.+2.2j, 20.+2.2j, 30.+2.2j, 40.+2.2j, 50.+2.2j], dtype=complex64)

In [134]:
a = np.array([10, 20, 25, 30, 35, 40])

In [135]:
a%2

array([0, 0, 1, 0, 1, 0])

In [136]:
a[a%2]

array([10, 10, 20, 10, 20, 10])

In [137]:
a[a%2 == 1]

array([25, 35])

In [138]:
a[a%2 == 0]

array([10, 20, 30, 40])

In [139]:
(a%2 == 0).dtype

dtype('bool')

In [140]:
(a%2 == 1).dtype

dtype('bool')

In [141]:
bool.__bases__

(int,)

In [142]:
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 1000,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False,
 'override_repr': None}

In [143]:
a = np.random.rand(10)

In [144]:
a

array([0.62311957, 0.80228008, 0.86688259, 0.55451865, 0.50227258,
       0.64917295, 0.43630415, 0.89262995, 0.09319455, 0.69939841])

In [ ]:
#  'precision': 8 => 8 digits 

In [146]:
np.set_printoptions(precision =20)

In [147]:
a

array([0.6231195697197371 , 0.8022800803771283 , 0.8668825859572815 ,
       0.5545186531337273 , 0.5022725793267254 , 0.649172948310569  ,
       0.4363041506615033 , 0.8926299465530959 , 0.09319454938236982,
       0.6993984078506957 ])

In [ ]:

# threshold => number of digits will be executed

#### NAN 


In [150]:
a = np.random.randint(0, 1000, 30 )

In [151]:
a

array([653,  65, 213,  84, 501, 574, 727,   7, 122, 736, 406, 809,  87,
       258, 872,  87, 984, 882, 454, 884, 716, 147, 216, 225, 930, 138,
       402, 842, 888, 924], dtype=int32)

In [152]:
a.mean() 

np.float64(494.43333333333334)

In [153]:
a.std()

np.float64(328.5471740185198)