#### Fancy Indexing 

In [2]:
import numpy as np

In [3]:
a = np.random.randint(9, 100, 20)
a

array([93, 45, 63, 72, 20, 12, 14, 72, 52, 13, 35, 73, 47, 28,  9, 79, 98,
       95, 38, 49], dtype=int32)

In [4]:
a[10]

np.int32(35)

In [5]:
# fancy indexing 
a[    [10, 15]     ]

# the outside bracket is to tell python there is a list of information that need to be achieved 

array([35, 79], dtype=int32)

# the main message is that there is different way to getting in dex from an array.  
1) indexing to get back one value
2) indexing with [ ] to get back multiple value 
3) mum.py directly

#### Boolean  indexing


In [9]:
a = np.array([10, 15, 20, 35, 35, 40])
a[[3, 5]]

array([35, 40])

In [12]:
a[ [ True, False, True, False, False, True]]

array([10, 20, 40])

#### Views vs copies

In [13]:
a = np.arange(0, 101, 5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [14]:
b = a[3:10]
b

array([15, 20, 25, 30, 35, 40, 45])

In [15]:
# b is a view on a 
b[0] = 999 
b[4] = 888
b

array([999,  20,  25,  30, 888,  40,  45])

In [16]:
a

array([  0,   5,  10, 999,  20,  25,  30, 888,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [18]:
a[4] = 777
a

array([  0,   5,  10, 999, 777,  25,  30, 888,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [19]:
a

array([  0,   5,  10, 999, 777,  25,  30, 888,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [20]:
b

array([999, 777,  25,  30, 888,  40,  45])

In [21]:
b.base

array([  0,   5,  10, 999, 777,  25,  30, 888,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [22]:
a.base

In [23]:
type(a.base)

NoneType

In [24]:
a is b.base

True

In [27]:
c = a[[3,4,5,6, 7, 8, 9]]
c,

(array([999, 777,  25,  30, 888,  40,  45]),)

In [28]:
c.base

In [29]:
type(c.base)

NoneType

In [ ]:

# is not a view on a,rather c is a copy value of a onto c 

In [30]:
d = np.copy(a)

In [31]:
a is d

False

In [32]:
a is c

False

In [33]:
a is b

False

In [34]:
b is a

False

In [35]:
a - d

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# make sure to understand whether you are copy value from an array or you are creating a view base of an array 

#### Selecting with boolean indexes 

In [36]:
a = np.random.randint(0, 100 ,20)

In [37]:
a

array([29, 52, 18,  6, 38, 93, 20, 18, 62, 53, 54, 55, 75, 48, 47, 86, 40,
       56, 89, 78], dtype=int32)

In [38]:
a[a>20]

array([29, 52, 38, 93, 62, 53, 54, 55, 75, 48, 47, 86, 40, 56, 89, 78],
      dtype=int32)

In [39]:
a[a<50]

array([29, 18,  6, 38, 20, 18, 48, 47, 40], dtype=int32)

In [40]:
a[a==2]

array([], dtype=int32)

In [41]:
a[a==62]

array([62], dtype=int32)

In [42]:
a.mean()

np.float64(50.85)

In [43]:
a[a > a.mean()]

array([52, 93, 62, 53, 54, 55, 75, 86, 56, 89, 78], dtype=int32)

In [45]:
a

array([29, 52, 18,  6, 38, 93, 20, 18, 62, 53, 54, 55, 75, 48, 47, 86, 40,
       56, 89, 78], dtype=int32)

In [46]:
a[a > a.mean()].mean()

np.float64(68.45454545454545)

In [47]:
a[a < a.mean()].mean() 

np.float64(29.333333333333332)

#### Evens and odds

In [48]:
a

array([29, 52, 18,  6, 38, 93, 20, 18, 62, 53, 54, 55, 75, 48, 47, 86, 40,
       56, 89, 78], dtype=int32)

In [53]:
a[a % 2 == 1]

array([29, 93, 53, 55, 75, 47, 89], dtype=int32)

In [54]:
a[a % 2 == 0]

array([52, 18,  6, 38, 20, 18, 62, 54, 48, 86, 40, 56, 78], dtype=int32)

#### Exercise 4

In [55]:
a = np.random.randint(0, 100 ,20)

In [56]:
a

array([70, 21, 87, 60, 58, 97, 54, 29, 24, 89, 99, 48, 43, 95, 14, 77, 58,
       67,  0, 39], dtype=int32)

In [57]:
a.max()

np.int32(99)

In [59]:
a[a % 2 == 1].mean()

np.float64(67.54545454545455)

In [63]:
b = a[[0, 19]]
b

array([70, 39], dtype=int32)

In [64]:
c = a[[0, -1]]
c

array([70, 39], dtype=int32)

In [83]:
d = a[a % 2 == 1]

In [84]:
d

array([21, 87, 97, 29, 89, 99, 43, 95, 77, 67, 39], dtype=int32)

In [85]:
d[0]

np.int32(21)

In [86]:
d[[0,-1]]

array([21, 39], dtype=int32)

In [87]:
f = np.random.randint(0, 1000, 20)
f

array([800, 897, 638, 852, 666,  12, 816, 768,  13, 617, 208, 169, 116,
       457, 654, 650, 245, 767, 188,  39], dtype=int32)

In [89]:
f.mean() 

np.float64(478.6)

In [88]:
f[f < f.mean() ]

array([ 12,  13, 208, 169, 116, 457, 245, 188,  39], dtype=int32)

In [92]:
g = f[f < f.mean() ].std()
g

np.float64(132.78535543230643)

In [93]:
f[f < g]

array([ 12,  13, 116,  39], dtype=int32)

#### complex conditions

In [94]:
a = np.random.randint(0, 100, 20)

In [95]:
a

array([96, 42, 24, 53,  8, 68, 60, 96, 14, 24, 97, 51, 64, 65, 13, 53, 48,
        0, 77, 86], dtype=int32)

In [97]:
a.mean()

np.float64(51.95)

In [96]:
# option 1: create a new variable to assign 
b = a[a%2 == 0 ]
b[b < a.mean()] 

array([42, 24,  8, 14, 24, 48,  0], dtype=int32)

In [98]:
a[(a%2 == 0) & 
  (a < a.mean())]

array([42, 24,  8, 14, 24, 48,  0], dtype=int32)

In [99]:
a[(a%2 == 0) | 
  (a < a.mean())]



array([96, 42, 24,  8, 68, 60, 96, 14, 24, 51, 64, 13, 48,  0, 86],
      dtype=int32)

In [100]:
a[(a%2 == 0) and 
  (a < a.mean())]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [101]:
a[(a%2 == 0) or 
  (a < a.mean())]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### Exercise 4

In [146]:
a = np.random.randint(0, 100, 20)
a

array([84, 81, 13, 12, 69, 80, 64, 89, 98,  9, 77, 26, 48, 15, 52, 66, 29,
        0, 63,  7], dtype=int32)

In [147]:
a.sort() 
a

array([ 0,  7,  9, 12, 13, 15, 26, 29, 48, 52, 63, 64, 66, 69, 77, 80, 81,
       84, 89, 98], dtype=int32)

In [148]:
a[a % 2 == 0]

array([ 0, 12, 26, 48, 52, 64, 66, 80, 84, 98], dtype=int32)

In [149]:
a.mean() 

np.float64(49.1)

In [150]:
# what is the smallest even number greater than the mean? 
a[(a % 2 == 0) &
  (a> a.mean())][0]

np.int32(52)

In [200]:
# what is the smallest even number greater than the mean? 
a[(a % 2 == 0) &
  (a> a.mean())].min()

np.int32(52)

In [201]:
# show all numbers either < mean - std or mean + std 
a[(a.mean() - a.std()) 
  | (a.mean() + a.std())]

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [202]:
a[a.mean() - a.std()] 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [203]:
a.mean()

np.float64(49.1)

In [204]:
a.std()

np.float64(31.328740798187212)

In [205]:
a.mean() - a.std()

np.float64(17.77125920181279)

In [206]:
a.mean() + a.std()

np.float64(80.42874079818722)

In [208]:
a[(a < (a.mean() - a.std())) | 
  (a > (a.mean() + a.std())) ]

array([ 0,  7,  9, 12, 13, 15, 81, 84, 89, 98], dtype=int32)

In [158]:
b = [a[a % 2 == 0] > a.mean()]
b

[array([False, False, False, False,  True,  True,  True,  True,  True,
         True])]

In [215]:
a[(a % 2 == 0) & (a < a.mean()) |
  (a % 2 == 1) & (a > a.mean())]

array([ 0, 12, 26, 48, 63, 69, 77, 81, 89], dtype=int32)

In [168]:
a[a % 2 == 0] 

array([ 0, 12, 26, 48, 52, 64, 66, 80, 84, 98], dtype=int32)

In [169]:
a.mean()

np.float64(49.1)

In [182]:
a[(a % 2 == 0) < (a.mean())] 


array([ 0,  7,  9, 12, 13, 15, 26, 29, 48, 52, 63, 64, 66, 69, 77, 80, 81,
       84, 89, 98], dtype=int32)

In [197]:
b = a[(a % 2 == 0) &
  (a < a.mean())]
b

array([ 0, 12, 26, 48], dtype=int32)

In [211]:
c = a[(a % 2 == 1) &
  (a > a.mean())]
c

array([63, 69, 77, 81, 89], dtype=int32)

#### Assigning via indexes

In [216]:
a

array([ 0,  7,  9, 12, 13, 15, 26, 29, 48, 52, 63, 64, 66, 69, 77, 80, 81,
       84, 89, 98], dtype=int32)

In [217]:
a[[3,7,9,2]]

array([12, 29, 52,  9], dtype=int32)

In [218]:
a[[3,7,9,2]] = 999

In [219]:
a

array([  0,   7, 999, 999,  13,  15,  26, 999,  48, 999,  63,  64,  66,
        69,  77,  80,  81,  84,  89,  98], dtype=int32)

#### Exercise 5.a



In [220]:
a = np.random.randint(0, 100, 40)
a

array([ 0, 82, 56, 24, 85, 24, 87, 14, 13, 63, 75, 18, 96, 18, 90, 49, 78,
       77, 59, 73, 75, 47, 56, 84, 15,  3, 89, 23, 39, 52, 68, 67, 28, 43,
       85, 24,  6,  7, 15,  5], dtype=int32)

In [221]:
a.mean()

np.float64(47.8)

In [222]:
a.mean() - a.std()

np.float64(17.64357448237606)

In [223]:
a.mean() + a.std()

np.float64(77.95642551762393)

In [224]:
a[(a > a.mean() - a.std()) &
  (a < a.mean() + a.std())]

array([56, 24, 24, 63, 75, 18, 18, 49, 77, 59, 73, 75, 47, 56, 23, 39, 52,
       68, 67, 28, 43, 24], dtype=int32)

In [226]:
a[(a > a.mean() - a.std()) &
  (a < a.mean() + a.std())].mean()

np.float64(48.09090909090909)

#### Exercise 5.b 

In [228]:
b = np.random.randint(0, 100, 10)

b

array([93, 49, 85, 50, 54, 65, 69,  6, 18, 59], dtype=int32)

In [242]:

b[np.arange(0, 10,2)]

array([49, 85, 54, 69, 18], dtype=int32)

In [246]:
b[np.arange(1, 10, 2)]

array([49, 50, 65,  6, 59], dtype=int32)

In [248]:

b[np.arange(0, 10,2)] = b[np.arange(1, 10, 2)]
b

array([49, 49, 50, 50, 65, 65,  6,  6, 59, 59], dtype=int32)

In [229]:
b[0] = b[1]

In [230]:
b

array([49, 49, 85, 50, 54, 65, 69,  6, 18, 59], dtype=int32)

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib
