In [1]:
import numpy as np

In [2]:
a = np.array([1000.0])

In [3]:
a

array([1000.])

In [4]:
a.dtype

dtype('float64')

In [5]:
a ** 100

array([1.e+300])

In [6]:
a ** 1000

C:\Users\dqthi\AppData\Local\Temp\ipykernel_12016\402965118.py:1: RuntimeWarning: overflow encountered in power
  a ** 1000


array([inf])

In [7]:
np.inf

inf

In [ ]:
# inf is infinite  

In [8]:
np.nan  == np.nan

False

In [9]:
np.inf == np.inf 

True

In [10]:
a 

array([1000.])

In [11]:
np.isinf(a)

array([False])

In [ ]:
n